### ISSUE TITLE
Error in the ConfigMgr 1910 Console 

### ISSUE THREAD

**Issue by AdamGrossTX** [rzander/sccmclictr#147]
I'm starting to see this error in the 1910 console AdminUI.logs. Not sure if it's a breaking issue, but just wanted to mention it if you haven't seen it.

The 'resource' (SCS_Extensions.Properties.Resources.resources) was not found.\r\nSystem.Resources.MissingManifestResourceException\r\nCould not find any resources appropriate for the specified culture or the neutral culture.  Make sure "SCS_Extensions.Properties.Resources.resources" was correctly embedded or linked into assembly "SCCMCliCtrWPF" at compile time, or that all the satellite assemblies required are loadable and fully signed.\r\n   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at System.Resources.ResourceManager.GetString(String name)
   at Microsoft.ConfigurationManagement.AdminConsole.Common.UtilityClass.TryGetStringFromAssembly(AssemblyDescription assemblyDescription, String resourceName, String& returnString)\r\n

**Comment by rzander** [comment]
thanks Adam, it's a good hint... I have the same errors. Will check that...

**Comment by rzander** [comment]
Fixed in https://github.com/rzander/sccmclictr/commit/8f2066e712aa054b0842db05f3a0fbcd9a4efadd
